name: Publish Docker image

env:
  #  NODE_ENV: 'production'
  REPOSITORY: erickartman/testtasknest

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Set image tag
        id: tag
        run: echo "image_tag=main-$(date +'%Y%m%d%H%M%S')-$(echo ${GITHUB_SHA::8})" >> $GITHUB_OUTPUT
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{env.REPOSITORY}}:${{ steps.tag.outputs.image_tag }}
